### ISSUE TITLE
Error in lift engine

### ISSUE THREAD

**Issue by greguintow** [prisma/prisma2#127]
I'm on Ubuntu 18.04, and I tried all kind of database and all the ways, I tried to clone photon repository and run the instructions but said migration-engine ENOENT, I tried to use prisma2 init with sqlite, mysql, postgres, postgres remotely and none works.
So I tried the entire day to make prisma2 works and didn't. So I'm reporting this issue because said the linux and macOS was tested and just Windows isn't working. But Linux is not working either.

**Comment by goof03** [comment]
Do you have try npm install in your prisma project ? Solve for me on archlinux
But all my lift command are very slow :
🚀  Done with 1 migration in 661.14s.

**Comment by pantharshit00** [comment]
@greguintow Can you please share the output of `uname -a`?


@goof03 You also please share the output of `uname -a` so that we can determine the architecture. Also, please tell which database you are using and how much existing data you have in your database. Also, please share your datamodel with us.

**Comment by e2goon** [comment]
@pantharshit00 

```

MINGW64_NT-10.0 DESKTOP-2SNH0TN 2.10.0(0.325/5/3) 2018-04-23 03:21 x86_64 Msys
```
![image](https://user-images.githubusercontent.com/45934/60994079-b93b5b00-a38a-11e9-8a7d-ba7bc8d3aecb.png)

- Windows 10 Pro
- VSCode
- Git Bash

**Comment by goof03** [comment]
Linux *** 5.1.16-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 3 20:23:07 UTC 2019 x86_64 GNU/Linux

I just have your default schema without any datas i try to setup a project.

I use Postgress in a docker container (but init with sqlite, Postgres init connect but do anything when selecting schema). Ho and prisma studio do nothing when i edit schema even after my first up migration cant see any of my model in UI but table is created in postgres database …

**Comment by divyenduz** [comment]
I can reproduce the slowness issue, that is being tracked here: https://github.com/prisma/lift/issues/49
Please use the above issue to report issues related to slowness. 

For this issue, let us focus on the `ENOENT` issue, does that still persist for you @greguintow with the latest Prisma2 CLI version `2.0.0-preview-1`

**Comment by pantharshit00** [comment]
I can no longer reproduce the `ENOENT` issue with `2.0.0-preview-1`.

@e2goon Windows is currently not supported, it is being tracked here: #4 

Closing this now, please report back if issues are still persistent

**Comment by herbertpimentel** [comment]
I still have same error on Mac machine

> uname -a
Darwin iMac-de-Herbert.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

trying to use postgres 

"PostgreSQL 10.5+tjap-20180921 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit"

**Comment by pantharshit00** [comment]
I think the issue you are reporting is this one: https://github.com/prisma/lift/issues/10

Since you are using a Mac I think there shouldn't be any binary issues but we have this bug in which lift is unable to connect to postgres instance running outside or on a different port.
