### ISSUE TITLE
Error when using Photon to create new item with  2 relation connections

### ISSUE THREAD

**Issue by reinvanimschoot** [prisma/prisma2#317]
To give a bit of background, this is my data model (or at least part of it):

```
model User {
  // Meta
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  // Data
  auth0Id        String          @unique
  email          String          @unique
  firstName      String
  lastName       String
  picture        String
  private        Boolean         @default(false)
  userChallenges UserChallenge[] @relation(onDelete: CASCADE)
  following      Following[]     @relation(name: "UserFollowing", onDelete: CASCADE)
  followedBy     Following[]     @relation(name: "UserFollowed", onDelete: CASCADE)
  comments       Comment[]       @relation(onDelete: CASCADE)
  likes          Like[]          @relation(onDelete: CASCADE)
  tags           Tag[]           @relation(onDelete: CASCADE)
  challenging    Challenging[]   @relation(name: "UserChallenging", onDelete: CASCADE)
  challengedBy   Challenging[]   @relation(name: "UserChallenged", onDelete: CASCADE)
  reports        Flag[]          @relation(onDelete: NONE)
}

model Update {
  // Meta
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  //  Data
  text          String
  type          UpdateType
  secret        String        @unique
  userChallenge UserChallenge @relation(onDelete: NONE)
  comments      Comment[]     @relation(onDelete: CASCADE)
  likes         Like[]        @relation(onDelete: CASCADE)
  tags          Tag[]         @relation(onDelete: CASCADE)
}

model Like {
  // Meta
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  // Data
  user   User   @relation(onDelete: NONE)
  update Update @relation(onDelete: NONE)
}
```
The resolver I have trouble with is the one where I am trying to create a like:

```ts
export const likeMutations = extendType({
  type: 'Mutation',
  definition(t) {
    t.field('createLike', {
      type: 'Like',
      args: { updateId: idArg({ required: true }) },
      async resolve(parent, args, context) {
        return context.photon.likes.create({
          data: {
            update: { connect: { id: args.updateId } },
            user: { connect: { id: context.userId } },
          },
        });
      },
    });
  },
});
```

Whenever I try to call that resolver with the right arguments, I get the following error:

![Screenshot 2019-08-04 at 11 31 09](https://user-images.githubusercontent.com/35171567/62422015-dc1c0f00-b6ab-11e9-9715-661592f82d08.png)

I tried the same thing with creating a comment and I got the same error.

**Comment by divyenduz** [comment]
This is using Postgres, confirmed with @reinvanimschoot, will try a reproduction now.

**Comment by divyenduz** [comment]
I am able to reproduce, detailed error log in the reproduction but the following error is observed: 

Reproduction: https://github.com/divyenduz/p2-317

```
(node:48012) UnhandledPromiseRejectionWarning: Error: Error in Photon:
ConnectorError(NullConstraintViolation { field_name: "Like.cjyybo3xg00021px1vtvk9643, null, 1970-01-01 00:00:00, cjyybo3x200011px1ob3s8256, cjyybo3wg00001px1upexc7j0)."
})
    at PhotonFetcher.<anonymous> (/Users/divyendusingh/Documents/prisma/p2-317/node_modules/@generated/photon/index.js:35:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/divyendusingh/Documents/prisma/p2-317/node_modules/@generated/photon/index.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:48012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, o
r by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:48012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js
 process with a non-zero exit code.
```

**Comment by divyenduz** [comment]
This is not reproducible in the latest preview 6.

**Comment by divyenduz** [comment]
This is still reproducible in the latest preview.

**Comment by mavilein** [comment]
Fixed with: https://github.com/prisma/prisma/commit/b0df6842459f018a2178867ec728399cfcf47b25

The fix is available in a few minutes on `alpha`.

Just FYI: The bug had nothing to do with relations. The problem were the fields `createdAt` and `updatedAt` in this case. The arguments for the scalar fields in `createLike` were empty. We had a line that was not setting the default values for those fields in this case. Then the insert failed because the columns have to be not null.

**Comment by reinvanimschoot** [comment]
This doesn't seem to be fixed in preview7. Is this scheduled for the next preview?

**Comment by pantharshit00** [comment]
I tried this out and I am no longer able to reproduce this with `prisma2@2.0.0-preview-7, binary version: 33e5fc84b6bd61602f8d634beb558230ca3e3054`

![image](https://user-images.githubusercontent.com/22195362/63276597-46929900-c2c1-11e9-9ddd-44d174bb58cf.png)


@reinvanimschoot Please make sure you have run `prisma2 generate` in order to update the binary in your node_modules after installing the new version globally.

**Comment by reinvanimschoot** [comment]
I did all that and I still get the same error:

<img width="957" alt="Screenshot 2019-08-19 at 18 28 37" src="https://user-images.githubusercontent.com/35171567/63282509-4093bc80-c2af-11e9-8966-d1f6952732db.png">

**Comment by reinvanimschoot** [comment]
Just tried it again, removed node_modules, checked version to be the same as yours, did yarn install, did prisma2 generate, still the same error

<img width="1440" alt="Screenshot 2019-08-19 at 18 34 52" src="https://user-images.githubusercontent.com/35171567/63282858-10005280-c2b0-11e9-8f4b-9fe344538b90.png">

<img width="715" alt="Screenshot 2019-08-19 at 18 35 32" src="https://user-images.githubusercontent.com/35171567/63282911-29a19a00-c2b0-11e9-8173-bf53e640756a.png">


Unless there is some other cache somewhere?

**Comment by pantharshit00** [comment]
Well, if possible can you please make a git repository of the project and share that with us.

**Comment by reinvanimschoot** [comment]
I had to do the migration again as well, it works now, though I found another bug. But this can be closed!
