### ISSUE TITLE
'prisma2 init' with mysql leads to react error on MySQL8 because of authentication problem

### ISSUE THREAD

**Issue by Parilar** [prisma/prisma2#46]
**Describe the bug**

> React will try to recreate this component tree from scratch using the error boundary you provided, App.
> Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
> The above error occurred in one of your React components:
>     in Unknown
>     in div (created by Box)
>     in Box
>     in div (created by Box)
>     in Box
>     in div (created by Box)
>     in Box
>     in Unknown
>     in div (created by Box)
>     in Box
>     in Unknown
>     in App
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, App.
> Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

**To Reproduce**
1. Run 'prisma2 init'
2. Select Mysql
3. Enter your data
4. Select Connect
5. See error

**Expected behavior**
The database select screen 

**Versions (please complete the following information):**
 - Connector: MySQL
 - Prisma Server: 0.0.84
 - OS: macOS 10.14.3

**Comment by hyochan** [comment]
@pantharshit00 Above error could be fixed by the command `ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'`. When done this, `error messsage` is gone and react `error` message appears as the first issue post.

**Comment by timsuchanek** [comment]
Belongs to https://github.com/prisma/prisma2/issues/278

**Comment by priley86** [comment]
seeing this one too in my prisma2 playground... fairly easy to reproduce now if it helps... just target this commit and run `npm run start` (starting my app's Docker containers locally):
https://github.com/priley86/how-to-graphql/commit/b5763c475b223c32d29c092545ddeb738ccca208

You'll see these:
```
prisma      | React will try to recreate this component tree from scratch using the error boundary you provided, App.
prisma      | The above error occurred in the <DevComponent> component:
prisma      |     in DevComponent (created by Context.Consumer)
prisma      |     in Unknown
prisma      |     in App
prisma      | 
prisma      | React will try to recreate this component tree from scratch using the error boundary you provided, App.
prisma      | Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```

**Comment by divyenduz** [comment]
@priley86 What terminal are you using? I have a hunch that this might be related to a specific terminal.

**Comment by divyenduz** [comment]
@kleydon can you please create a minimal reproduction? and what error do you see exactly? Thanks

**Comment by kleydon** [comment]
@divyenduz I see exactly the same thing that @priley86 described above (on August 11th); he has provided one example commit. 
The same problem also occurs from this repo: 
https://github.com/CaptainChemist/blog-prisma2/tree/staging
To reproduce, in the projects root directory type:
`npm run build`
`npm run start`
(You may need to wait for a minute or two for the React-related error messages to appear.)

**Comment by priley86** [comment]
the last time I tried this was w/  `prisma2@2.0.0-preview-5`. Hoping to pull down latest again soon and see what issues are resolved...
https://github.com/priley86/how-to-graphql/blob/master/backend/prisma/Dockerfile#L2

**Comment by bamne123** [comment]
I'm experiencing the same React error above using iTerm2 (mac), with prisma2@2.0.0-preview-12, and mysql 5.7

**Comment by Constans** [comment]
Same error with prisma2@2.0.0-preview-13 & mysql 5.7, both running in Docker (prisma2 running in 10.16.0).

```
The above error occurred in the <DevComponent> component:
    in DevComponent (created by Context.Consumer)
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```

**Comment by bamne123** [comment]
![Screen Shot 2019-09-28 at 4 47 21 PM](https://user-images.githubusercontent.com/10872173/65815639-c17b9780-e20f-11e9-88f5-f40cfd072835.jpg)

**Comment by janpio** [comment]
Hey everyone who posted here, we are on `2.0.0-preview019` now, could you please install the newer version and confirm if or if not you are still getting the React error when trying to connect to MySQL? Thanks!

**Comment by janpio** [comment]
We will replace the existing `init` wizard with a much simpler version in `2.0.0-preview020`, so this problem will be gone after that 🚀
