### ISSUE TITLE
Prisma2 dev 'cannot destructure property "dmmf"'

### ISSUE THREAD

**Issue by BiscuiTech** [prisma/prisma2#999]
I am recently having this issue where running `prisma2 dev` seems to work fine. The interface at lh/5555 loads up but shows "getting things ready" for about 5 minutes. Then, this error happens:
![image](https://user-images.githubusercontent.com/17841919/69658623-8dbfc100-104a-11ea-8593-f2d10827a140.png)

In the console, i get this: 
`Failed to generate Photon client: Error: Error: Command failed with ENOENT: /home/biscuitech/.nvm/versions/node/v13.1.0/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf
spawn /home/biscuitech/.nvm/versions/node/v13.1.0/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 ENOENT`
I can't seems to make prisma2 dev work. 

Before trying prisma2 dev, I ran prisma2 lift save & up with sucess. But after running prisma2 dev, I have this error on `lift up`:
https://gist.github.com/BiscuiTech/4fc7058b55379ed6fec13c2f6f8f107c

After trying prisma2 dev again, it crashes right away with this error:

![image](https://user-images.githubusercontent.com/17841919/69659225-c01dee00-104b-11ea-91e9-452b5c8ab415.png)

**Comment by BiscuiTech** [comment]
The stack trace seems to correspond to the same trace as this error #919.

**Comment by frbrz** [comment]
Hi. This is the same error (```Command failed with ENOENT [...] query-engine-linux-glibc-libssl1.1.0 cli --dmmf [...]```) that I reported here: #993. I'm seeing the exact same error in the web interface at localhost:5555.

**Comment by pantharshit00** [comment]
Can you please all try this again with the latest preview(preview017)? The binary names that you have mentioned are referring to the old names so I think you are using an old version of Prisma 2.

If you on Linux, please use this command to install prisma2(if you don't have a nvm or similar tool or haven't set the permission of npm global bin properly):
```
sudo npm install -g --unsafe-perm prisma2
```

**Comment by pantharshit00** [comment]
Update: I am able to reproduce this on windows with the latest alpha: prisma2@2.0.0-alpha.360, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293

![image](https://user-images.githubusercontent.com/22195362/69727768-28062e80-1149-11ea-9cb8-ac6ff2d9654e.png)

I will check on mac as well with the latest alpha.

**Comment by pantharshit00** [comment]
I am unable to reproduce this on mac though

**Comment by tmfprlt1234** [comment]
> Update: I am able to reproduce this on windows with the latest alpha: prisma2@2.0.0-alpha.360, binary version: 6159bf3a263921c3c28ee68e2c9e130b5a69c293
> 
> ![image](https://user-images.githubusercontent.com/22195362/69727768-28062e80-1149-11ea-9cb8-ac6ff2d9654e.png)
> 
> I will check on mac as well with the latest alpha.

i also installed prisma2@alpha, but not changed, at vmware - centos 7

**Comment by kripod** [comment]
I just encountered this while running `yarn prisma2 dev` on Windows 10 x64. The stack trace could hardly be caught, due to the interactive behavior of `prisma2 dev` constantly rewriting the entire screen.

![image](https://user-images.githubusercontent.com/14854048/69729800-3d6a6100-1127-11ea-9a66-20dc3ff6217e.png)

The issue can be reproduced by cloning [this repo](https://github.com/kripod/exigo), installing the dependencies and then running `yarn generate` in the `server` directory, followed by `yarn develop` or more specifically, `yarn prisma2 develop`.

**Comment by BiscuiTech** [comment]
> Can you please all try this again with the latest preview(preview017)? The binary names that you have mentioned are referring to the old names so I think you are using an old version of Prisma 2.
> 
> If you on Linux, please use this command to install prisma2(if you don't have nvm or similar tool or haven't set the permission of npm global bin properly):
> 
> ```
> sudo npm install -g --unsafe-perm prisma2
> ```

I do have nvm. I'm on Win10 running 20H1 and WSL2. I'll try cleaning the whole npm cache and reinstalling everything.

**Comment by CaptainChemist** [comment]
I'm having this exact issue when trying to run within a docker environment. Here's a repo, it is the prisma2 hello starter where I added a Dockerfile and docker-compose.yml. In this case, I'm using `npx` as well as prisma v17.1 and photon v17.1 packages added to the package.json

https://github.com/CaptainChemist/prisma2-17.1-enoent-err

If you download the project and then run `docker-compose build` followed by `docker-compose up` the backend and studio containers both have the `query-engine-debian-openssl-1.1.x` file. For completeness, in order to get into those containers you have to run one of the following from the command line after you do a docker-compose up:
`docker exec -it backend bash`
`docker exec -it studio bash`

The problem is that when I run `prisma2 dev` that the docker-compose output has an error: Failed to generate Photon client: Error: Error: Command failed with ENOENT: /app/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf

I'm not sure why that is looking for a different query engine. In any case, hopefully running in a docker container will allow people on different platforms to have the same environment, but that's interesting that people are seeing the same issue outside of debian docker instances.

**Comment by pantharshit00** [comment]
I can confirm this on linux, see https://github.com/prisma/prisma2/issues/993#issuecomment-559207019

**Comment by timsuchanek** [comment]
Thanks a lot for your input everyone! We just released a new alpha, which should fix this issue in the `prisma2 dev` command.
Please let me know, how it goes for you :)

**Comment by tmfprlt1234** [comment]
i updated new to new alpha, so i cant see this issue anymore.
but when i open localhost:5555 in my browser(chrome,ie) it seems like this ->

**Comment by timsuchanek** [comment]
Thanks @tmfprlt1234! The big plus should be gone now in the latest alpha (369).
We'll do a patch release now including a fix for this!
Let me know if it's still an issue for you and I'll reopen this issue.

**Comment by BiscuiTech** [comment]
I just updated to preview 17.2 and still have this issue:
![image](https://user-images.githubusercontent.com/17841919/69815858-37c35880-11c5-11ea-914c-719352d1d9a0.png)

**Comment by BiscuiTech** [comment]
I just updated and it seems that the original issue was fixed. But now I have this issue on my localhost db connection: 
![image](https://user-images.githubusercontent.com/17841919/69816119-bddf9f00-11c5-11ea-9b31-38c7b98234b7.png)

It comes from a "failedCalculatedSteps" file the prisma framework generated on the error.

**Comment by janpio** [comment]
@BiscuiTech Please open a new issue and someone will take a look into reproducing this.
